apiVersion: base.scone.cloud/v1beta1
kind: SGXPlugin
metadata:
  name: sgxplugin
spec:
  autoUpdate: true
  image: "${IMAGE_REPO}/sgx-plugin:${VERSION}"
  imagePullSecrets:
   - name: scone-operator-pull
  imagePullPolicy: Always
  namespace: scone-system
  podAnnotations:
    scone-operator/inject-pull-secret:  "true"

