apiVersion: base.scone.cloud/v1beta1
kind: LAS
metadata:
  name: las
spec:
  autoUpdate: true
  image: "${IMAGE_REPO}/las:no-epid-production-5.8.0-rc.4"
  imagePullSecrets:
   - name: scone-operator-pull
  imagePullPolicy: Always
  namespace: scone-system
  podAnnotations:
    scone-operator/inject-pull-secret:  "true"

